### ISSUE TITLE
Forms Presenters TODO

### ISSUE THREAD

**Issue by Cheesebaron** [Cheesebaron/Cheesebaron.MvxPlugins#34]
- [x] Fix Android Project to use new `Application` class from Xamarin.Forms
- [x] Revisit the NavigationHost etc. on Android. Is it necessary?
- [x] Expand the Sample to do a bit more than it does now
- [x] Deploy Movies sample on iOS to see if everything works fine (it should, code is updated)

**Comment by MarcosCobena** [comment]
I've pushed today a WIP on the Presenters normalization:

https://github.com/Cheesebaron/Cheesebaron.MvxPlugins/tree/formspresentersnormalization

I need some more time to figure out how to work with current Android implementation, so maybe I'll end up touching the 2nd point (NavigationHost and so on).

**Comment by Cheesebaron** [comment]
I think... The NavigationHost is not necessary as the only thing it does is figure out how to get a page such that the `PushAsync`, `PopAsync`, etc. can be called for navigation. This can now be achieved with that `Application` object from Forms, which gives you the main `Page` which is enough for that. So what I meant by normalization was to do as is done on iOS and WP on Android as well.

**Comment by MarcosCobena** [comment]
OK, got it, I'm working on this a little bit today. Will come back with news. Thanks!

**Comment by Cheesebaron** [comment]
Alright, I will probably be able to do some work on this in the weekend, so if there are any lose ends please do tell :)

**Comment by MarcosCobena** [comment]
Hey Tomasz,

We've just pushed a bunch of changes to the plug-in taken from a real world project we're working on. The way we were doing the plug-in had some troubles, for instance:
- We were forcing plug-in consumers to take FormsPresenters.Droid's Resources file, instead of the final app's one, so local pictures couldn't be found, i.e.
- We were getting plenty of "you must call Forms.Init() prior to consuming it" due to the initialization chain, so we moved such to final app. We've added some TXT files which guide users on how to set-up their projects, in a similar way to how MvvmCross manages that

We currently have no time to work on the iOS and Windows Phone parts, but should be pretty straightforward to change current code to reflect last changes. If you could please help us here we could align the 3 platforms to the same point. Anyway I'll personally try to take some spare time to do this.

We hope you like it! Happy day!

Marcos

**Comment by MarcosCobena** [comment]
Hi,

I've just moved the Movies sample here, and adapted it to the latest FormsPresenters plug-in.

Although I've tested iOS Project builds fine, I haven't been able to try to deploy it, it's still pending.

Enjoy!

Marcos

**Comment by Cheesebaron** [comment]
Alright. If you need to use TMDB you probably need to generate a new API key. My account may or may not have been nuked or the API key has been at least.

**Comment by Dave-T** [comment]
@MarcosCobena I notice in your sample your App class in the PCL project is derived from MvxApplication. I noticed that in @Cheesebaron's new Forms Presenters plugin, he has an MvxFormsApp class derived from Xamarin's Application class.

My question is: When should the MvxFormsApp class be used with the new plugin vs the MvxApplication class?

Thanks!
Dave

**Comment by MarcosCobena** [comment]
Hi @Dave-T, we recently moved from @Cheesebaron's approach (the one you mention with MvxFormsApp) to the MvxApplication one. If you have a look to the FormsPresenters projects, you'll find some TXT files with instructions on how to run them all.

**Comment by Dave-T** [comment]
Thanks, @MarcosCobena! I appreciate the information.
